platform:
    - x64

cache:
    - C:\Users\appveyor\.esy\3_\i
    - C:\Users\appveyor\.esy\source-tarballs

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 9 x64
    - npm install
    - npm install -g yarn
    - npm install -g esy@next
    # Install cygwin
    - npm run build-cygwin
    - cd re
    # Retry is necessary due to esy/esy#413 and esy/esy#414
    - appveyor-retry esy install

# 'max-old-space-size' needs to be set for large NPM uploads,
# otherwise node will crash with an out-of-memory error
environment:
  NODE_OPTIONS: --max-old-space-size=4096
  NPM_TOKEN:
    secure: h3hweU1D+fx2hyHtCSUHVkR7pKf7XpCEwC0/E/a+7vxnus3hArWb4w0WjynzOPJ+

build_script:
    - esy build
    - esy b dune runtest
    - cd ..

test: off

deploy_script:
  - npm --version
  - yarn --version
  - echo Deploying...
  - ps: |
      if ($ENV:PLATFORM -eq "x64")
      {
        "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
        iex "yarn pack"
        iex "npm publish esy-bash-v0.2.2.tgz --verbose"
      }
    on:
      branches: master
